name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTkxZWVlYmUtODNmMS00YWUzLTk1NmQtN2FkNThjMWMyZmVjIiwidGVuYW50X2lkIjoiYmU1YTIyM2FiYjVjZjQ0NTU5MTQzNGFiYjVjYjFmYzg1YzU1ODE0ZTk0MmNjMDM0Y2I1YWI1YThiM2ViMDVjMyIsImludGVybmFsX3NlY3JldCI6IjJiNDE2ZDQ2LWJiZjQtNGMzMy04ZTA5LTljNWYzN2RkOGJiMyJ9.6Ha8GnEYQ4lgP10e5Vv9Lwg2-tl_kDPDVvTrVaWDUxg"
JWT_SECRET="SECRET"